### ISSUE TITLE
Add FAQs page or something similar? 

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/website#10]
I really like your front page of usegalaxy.eu :smile: and was wondering - what about having a link to an FAQs page or something? 

e.g. how would users know that they have to use ftp to get files >2GB (and how to do it)?

I know it must be in the Galaxy documentation somewhere but imho that info is super important (as getting data in is the first step to using Galaxy and a lot of the fastq/BAM files our users have are over >2GB) so having that info closer (more easily accessible) for users e.g. one-click away would be good I think

Also having an prominent/obvious link to where users can support (e.g. Biostars) would be good, or to wherever they're supposed to get help.

**Comment by erasche** [comment]
Whenever you try to upload a file larger than 2GB, it complains and says to use FTP

![auswahl_343](https://user-images.githubusercontent.com/458683/36790028-c16f6278-1c93-11e8-8620-917ba70223c5.png)

Clicking the FTP button mentions you should connect to `ftp://...` with your standard creentials.

![auswahl_344](https://user-images.githubusercontent.com/458683/36790029-c18ae1e2-1c93-11e8-9d5d-3e9ffd011f43.png)

Is that enough to help users or would you think more information would be helpful?

**Comment by erasche** [comment]
Additionally, if they try and open a browser to the FTP site, https://ftp.usegalaxy.eu/, I've shown an FTP info page which has some documentation.

**Comment by mblue9** [comment]
I think this would be good to test out with a few users new to Galaxy. As my feeling is users may still waste time faffing around trying to get their files in (after the initial error they get when they try to upload) but maybe I'm underestimating them :)

**Comment by erasche** [comment]
Definitely. I think there will be a *huge* leap between "you need to use ftp" and the user being able to successfully download, install, and operate an FTP client. I can't wait until they implement chunked uploads https://github.com/galaxyproject/galaxy/issues/573 and we can kill FTP except for the users who really need it.

I don't think you're underestimating, it would be better if we linked to some documentation on "here is where to download an ftp client for your platform, here are detailed instructions, here are the exact server connection parameters" would significantly improve the success rate of people completing this task.

**Comment by mblue9** [comment]
Cool thanks for the link to that issue!

Yeah I ended up having to make a doc like that for our users 😄 see here:
[BIOIN-HowtoloadfilesintoGalaxyMelbourne-020318-1700-42.pdf](https://github.com/usegalaxy-eu/website/files/1773876/BIOIN-HowtoloadfilesintoGalaxyMelbourne-020318-1700-42.pdf)

**Comment by erasche** [comment]
How do you link to it? How do users know where to find that PDF?

**Comment by mblue9** [comment]
I exported that PDF, it lives in Confluence, the documentation system used (and admin-ed) by our group... which is now about to be trialled much wider by other groups in the hospital! :smile: 🎉

**Comment by mblue9** [comment]
In case you're interested to know, our Galaxy front page has a "Knowledge Base" button that links to info we will provide for users in Confluence, see below

<img width="891" alt="screen shot 2018-03-04 at 4 32 12 pm" src="https://user-images.githubusercontent.com/5591821/36942600-68fed878-1fca-11e8-9006-c680fc2a17d9.png">

**Comment by bgruening** [comment]
I think we need a FAQ site for all the small things people wonder will ask. Begins with Quota, might end citations/funding, CSA ... I hope most of the Q are links to the Galaxy hub in the end. Or the entire FAQ can be stored on the hub as part of our usegalaxy.eu hub site ...

**Comment by mblue9** [comment]
Yeah, I think you can't avoid the need for some sort of FAQ. That "Knowledge Base" button above on our front page leads to this page:
<img width="983" alt="screen shot 2018-03-05 at 12 51 38 pm" src="https://user-images.githubusercontent.com/5591821/36954336-56e7f6c8-2075-11e8-8708-8df1e44bf3bd.png">


which is currently completely empty (I need to add info in there asap!) I'm also hoping most will just be links to the Galaxy hub, I certainly don't want to reinvent the documentation wheel!  

But most importantly, imo some sort of FAQ/note is needed for data backup and storage (to cover your a*ses) - what accountability/responsibility are you accepting for the Users' data?

e.g. see this from Galaxy-QLD front page:
<img width="524" alt="screen shot 2018-03-05 at 12 42 40 pm" src="https://user-images.githubusercontent.com/5591821/36954171-5f4ac7d8-2074-11e8-8ffe-51faa9f568f9.png">

Note the "We do not backup user data" and "Data might be deleted from accounts inactive for six months or more". Something like that is really important to have imho, a clear statement of the scope of responsibility.

There's a similar note on the front page of Galaxy Melbourne (they also have a note on running jobs):
<img width="514" alt="screen shot 2018-03-05 at 12 43 27 pm" src="https://user-images.githubusercontent.com/5591821/36954202-8989e290-2074-11e8-8ed4-27753bb2388e.png">

**Comment by erasche** [comment]
- we now have a quota/storage/policy-y box in our carousel
- the "Help → Galaxy Help" now links to the new help.galaxyproject.org which we will use for FAQ / problems. We can pin messages there and we can pin one for dealing with common issues
