### ISSUE TITLE
Galaxy in RDMkit

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/website#1023]
Once [this PR](https://github.com/elixir-europe/rdmkit/pull/961) gets merged.

**Comment by bgruening** [comment]
URL is https://rdmkit.elixir-europe.org/galaxy_assembly

I liked the graphics from the poster a lot, maybe we can include it in the blog post.

**Comment by beatrizserrano** [comment]
addressed here: https://github.com/galaxyproject/galaxy-hub/pull/1684
