### ISSUE TITLE
some missing posts

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#106]
If anyone wants to generate some posts please help ...

- [x] GCB presentations about Bioconda, Clip-Explorer, RNA-workbench with @Florian-H-Lab, @eggzilla
- [x] GalaxyProteomics Workshop in Prag
- [x] new cloud with more power, de.NBI sponsored
- [x] HiC workshop in Luzern 9-10.10
- [x] Biohackathon in paris
- [x] european Galaxy days in November in Freiburg (https://galaxyproject.org/events/2018-europe-dev/)
- [x] @erasche post over RZ paper chimera/cyborg

**Comment by erxleben** [comment]
all done
