### ISSUE TITLE
blog post about EGI conference and our participation 

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#1129]
ping @elek-tron-ich @sanjaysrikakulam

**Comment by sanjaysrikakulam** [comment]
I will draft one.

**Comment by sanjaysrikakulam** [comment]
Here is the [PR](https://github.com/galaxyproject/galaxy-hub/pull/2090) for the blog post.

**Comment by sebastian-schaaf** [comment]
We are aware - just use 'sebastian-schaaf' next time for notifications 😉
