### ISSUE TITLE
Finalise single cell galaxy subdomain

### ISSUE THREAD

**Issue by nomadscientist** [usegalaxy-eu/website#1154]
Outstanding CoFest work last week!
Last remaining things:

- [x] There was the minor issue of the 'Single cell tools' label not working (1 line missing somewhere)
- [ ] Change the colour - purple
- [x] Redirect link from HCA instance (https://humancellatlas.usegalaxy.eu)
- [x] Review/merge this: https://github.com/usegalaxy-eu/website/pull/1158
- [x] ~~Hide/delete HCA instance~~ (moved to usegalaxy-eu/infrastructure-playbook#941)
- [x] Instructions for us on how to proceed in future as new tools are made, how do we get them to the appropriate section and/or create new ones? Do we raise an issue each time, for example?

@kysrpex

**Comment by kysrpex** [comment]
I created a separate issue usegalaxy-eu/infrastructure-playbook#941 for deleting the HCA instance since it will be inaccessible anyway.

**Comment by kysrpex** [comment]
- [ ] Change the colour - purple

@nomadscientist Visit usegalaxy-eu/infrastructure-playbook#940 and comment.
