### ISSUE TITLE
Bibliography entries without publication year break Jenkins

### ISSUE THREAD

**Issue by kysrpex** [usegalaxy-eu/website#1163]
Kind reminder that bibliography entries without publication year [cause the Jenkins project to fail](https://build.galaxyproject.eu/job/usegalaxy-eu/job/website/4714/). This has already happened in the past, see #1125.

I know that we should better integrate Jenkins and GitHub (or add something to lint the bib file), but for the time being let's add the publication year to [this publication](https://github.com/usegalaxy-eu/website/commit/cdc9072a02828cc8155ee27d17dac73503cc9f50) so that things are working again.

**Comment by bgruening** [comment]
Fixed, thanks for reporting.
