### ISSUE TITLE
TIaaS page updates

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#137]
This page https://galaxyproject.eu/tiaas should include a nice image and a big fat link to the training material.

**Comment by bgruening** [comment]
It would be also nice if we could have a more detailed post about TIaaS. I would only find that one atm: https://github.com/usegalaxy-eu/website/blob/master/_posts/2018-07-03-tiaas.md

If everyone feels comfortable to advertise this Service more broadly such a post could be linked in twitter, linkedin etc ...

@erxleben something you would like to start?

**Comment by erasche** [comment]
Oh, that was wip and shouldn't've been pushed.

Advertising, can you give me a week to get everything together first?

**Comment by bgruening** [comment]
Sure, see `If everyone feels comfortable to` :)

**Comment by erasche** [comment]
has picture / link to materials / link to workflow testing now
