### ISSUE TITLE
Consolidate rna.usegalaxy.eu Training sections?

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/website#184]
Hi,

Just noticed that it looks like there are 2 training sections on the rna.usegalaxy.eu page, this new one with the matrix

<img width="738" alt="screen shot 2019-02-08 at 11 22 21 am" src="https://user-images.githubusercontent.com/5591821/52451914-0e353400-2b95-11e9-8603-b9a9412bd236.png">

and then an older one further below

<img width="745" alt="screen shot 2019-02-08 at 11 22 34 am" src="https://user-images.githubusercontent.com/5591821/52451926-1a20f600-2b95-11e9-9b99-4c575ba2ac2c.png">

Wondering if they should be consolidated? e.g. moving the Training heading and small paragraph up after the Get Started, before the matrix?

**Comment by bgruening** [comment]
Makes sense to me. @pavanvidem?

**Comment by pavanvidem** [comment]
Sure, I thought that too. I will merge them. Thanks, @mblue9  for the suggestion.

**Comment by pavanvidem** [comment]
@mblue9 this was done https://github.com/usegalaxy-eu/website/pull/190
