### ISSUE TITLE
paper post for https://doi.org/10.1093/bioinformatics/btz107

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#191]
https://doi.org/10.1093/bioinformatics/btz107

free access link:
https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz107/5317160?guestAccessKey=a8c842e6-6bd0-4dc1-a4b5-8cf8281a9a5b

**Comment by bgruening** [comment]
@stephanflemming @simonbray this issue is for you both. It needs to contain many informations and a link to https://cheminformatics.usegalaxy.eu :)

**Comment by simonbray** [comment]
I'll do this.
