### ISSUE TITLE
19.01 update news item

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#205]
* [ ] Include a link to a how-to for how to clear the browser cache.

**Comment by erasche** [comment]
This should not be necessary, it has never been in previous upgrades despite JS and CSS changes.

Caching directives are only applied to CSS+JS files, and these are cache-busted by Galaxy with a timestamp set to start time. If the upgrade had completed successfully I do not believe you would have seen the partial state that you did. 

If we need to make this notice, to clear cache, then this is a bigger Galaxy problem.

**Comment by erasche** [comment]
https://github.com/galaxyproject/galaxy/pull/7527

**Comment by erasche** [comment]
Oops, wrong issue.

**Comment by erasche** [comment]
9915b7f98e65418ee9c308559b29995b4b67fe95
