### ISSUE TITLE
Roscoff event page not showing

### ISSUE THREAD

**Issue by gmauro** [usegalaxy-eu/website#206]
The remote event page does not appear in the middle frame

**Comment by bebatut** [comment]
I am not sure to understand what you mean.

The event appears for me:

![screenshot 2019-03-05 at 13 53 59](https://user-images.githubusercontent.com/1842467/53806770-30309500-3f4e-11e9-93f8-b9b58c167802.png)

**Comment by gmauro** [comment]
from https://usegalaxy.eu/, if you click on the event link , you will see a blank page in the middle frame

**Comment by bebatut** [comment]
ah ok. sorry I misunderstood

**Comment by erasche** [comment]
I'll fix it
