### ISSUE TITLE
missing posts

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#217]
- [x] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5838928/
- [x] https://nature.com/articles/s41598-019-40883-1

I also found this here: https://scholar.google.com/scholar?hl=de&as_sdt=0%2C5&q=acknowledgments+%22Freiburg+Galaxy+Team%22&btnG= if this is interesting for Rolf at some point.

**Comment by bgruening** [comment]
* https://www.nature.com/articles/s41598-019-40883-1

**Comment by bgruening** [comment]
* Post about the maxquant wrapper and the msconvert wrapper, both are pretty important for the masspec community. msconvert wrapper had a poster at gcc

**Comment by erxleben** [comment]
done
