### ISSUE TITLE
external event links do not open

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#223]
You need to open them in a new tab, which most of the people are not doing ... so they all get a white page at best.

**Comment by erasche** [comment]
This is either due to:

- http links
- the linked site setting X-Frame-Options to something like sameorigin, preventing us from embedding the content.

E.g. galaxyproject.org works, elixir and roscoff don't.

**Comment by OlegZharkov** [comment]
> You need to open them in a new tab, which most of the people are not doing ... so they all get a white page at best.

is it still relevant? Can you give me an example please?

**Comment by OlegZharkov** [comment]
I don't see an issue here, I'll close it for now. Please feel free to re-open this, if you think otherwise, I'll then do my best to fix it.
