### ISSUE TITLE
Galaxy interface takes long (~ 2 minutes) to load on poor connection

### ISSUE THREAD

**Issue by pvanheus** [usegalaxy-eu/website#329]
My connection here in Khartoum has 10% packet loss when its doing well. A result is that the Galaxy interface takes long to load - here is a timing diagram:

![image](https://user-images.githubusercontent.com/4154788/67030738-5b987680-f110-11e9-96a7-810b108d7421.png)

Total load time is approximately 2 minutes in this example. It looks like there are points where it pauses - e.g. some of the webhook related loads.

**Comment by pvanheus** [comment]
This is verified as also a problem from KNUST (Kwame Nkrumah University of Science and Technology) in Kumasi, Ghana.

This Firefox performance analysis shows that the page cache does not help much.

![image](https://user-images.githubusercontent.com/4154788/68587408-b9aa4680-048f-11ea-960e-6023a927343f.png)

**Comment by pvanheus** [comment]
More info on the page loading from Ghana:

![image](https://user-images.githubusercontent.com/4154788/68587850-c4191000-0490-11ea-8a6e-62133e85b20a.png)

![image](https://user-images.githubusercontent.com/4154788/68587893-d8f5a380-0490-11ea-9328-4d04210489ee.png)

**Comment by pvanheus** [comment]
From a user perspective the influences the initial page load time and also it influences whenever the page is reloaded e.g.

1) Going back to the Analyse data screen from the Multi-workflow screen
2) Loading the workflow editor and then going to execute a workflow
3) Navigating from the Data Library view to the Analyse data screen after importing data

**Comment by pvanheus** [comment]
Network performance from KNUST:

to Google

![image](https://user-images.githubusercontent.com/4154788/68588166-7d77e580-0491-11ea-8d61-a74e4381f4ce.png)

to usegalaxy.eu

![image](https://user-images.githubusercontent.com/4154788/68588199-8ff21f00-0491-11ea-8e23-dd6621c970f4.png)

**Comment by gmauro** [comment]
@pvanheus can you please try https://lite.usegalaxy.eu and let me know if it mitigates the issue?

**Comment by gmauro** [comment]
I have enabled data compression on https://usegalaxy.eu. 
Can you make a new try and let me know if is it better?

**Comment by pvanheus** [comment]
Thanks @gmauro I've been using the https://lite.usegalaxy.eu/ interface from various sites with poor networks and it seems to work a lot better. I was able to load the front page and workflow editor earlier at a site with reported download speed of 0.2 Mbit/s and 10% packet loss. I don't have a really good way to test in an objective manner though.

**Comment by bgruening** [comment]
@pvanheus can you also now test usegalaxy.eu again. it should also be much faster.

**Comment by gmauro** [comment]
Should be fixed.
