### ISSUE TITLE
paper for news section

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#342]
https://f1000research.com/articles/8-1877/v1 --> training paper

done

**Comment by bgruening** [comment]
* Miladi,M. et al. (2019) GraphClust2: Annotation and discovery of structured RNAs with scalable and accessible integrative clustering. GigaScience, 8.

* Föll,M.C. et al. (2019) Accessible and reproducible mass spectrometry imaging data analysis in Galaxy. GigaScience, 8.

**Comment by bgruening** [comment]
* Survey of metaproteomics software tools for functional microbiome analysis. (2020-01-09)

**Comment by bgruening** [comment]
* http://www.laborjournal-archiv.de/epaper/LJ_19_12/50/index.html

**Comment by erxleben** [comment]
> https://f1000research.com/articles/8-1877/v1 --> training paper

done
