### ISSUE TITLE
PGP news

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#356]
We need a blog post on our side to announce the availability of the PGP dataset.

* describe what PGP is
* link to  https://pgpukblog.wordpress.com/2019/12/18/reaching-for-the-stars-pgp-uk-multi-omics-data-now-also-available-on-galaxy-europe/
* mention training material for those data
* MIRACUM link?

@wm75 can you have a look here. And if available link this into Confluence? 
Thanks.

**Comment by erxleben** [comment]
@wm75 

**Human omics data from the Personal Genome Project now available on usegalaxy.eu!**

**What is PGP-UK?**
The Personal Genome Project UK (PGP-UK) is one of few projects world-wide to recruit all participants under open consent which enables PGP-UK to provide all patient data under open access. Currently PGP-UK provides open genome, trait, and health data. 

**PGP data accessible on Galaxy Europe**
All PGP-UK data is now freely accessible via Galaxy Europe and can be used e.g. as open access resource for [human multi-omics analysis](doi: 10.1038/s41597-019-0205-4). You can find the Genetic Data, Methylome Data, Transcriptome Data from PGP-UK in the Galaxy EU [shared data library](https://usegalaxy.eu/library/list#/folders/F43c642051145b1b6). 

**Training material**
To analyse PGP and other multi-omics data, the Galaxy Training Network provides a broad range of hands-on [training material](https://training.galaxyproject.org/) with a step-by-step guide through the whole data analysis workflow.

**Comment by wm75** [comment]
Thank you @erxleben!

**Comment by wm75** [comment]
#376

**Comment by bgruening** [comment]
Thanks.
