### ISSUE TITLE
News: should labels be clickable

### ISSUE THREAD

**Issue by stephanflemming** [usegalaxy-eu/website#412]
https://galaxyproject.eu/freiburg/news

Maybe it's a useful feature, that a click on a label should only show respective news items.

**Comment by simonbray** [comment]
fixed by @OlegZharkov

**Comment by beatrizserrano** [comment]
True, it's here https://github.com/usegalaxy-eu/website/pull/512. I think that we can close it, thanks for the heads up @simonbray 😄
