### ISSUE TITLE
UI bug starring outputs in workflows

### ISSUE THREAD

**Issue by mtekman** [usegalaxy-eu/website#43]
Un-toggling a starred output of a tool also untoggles (or appears to untoggle) other starred outputs if you mouseover and then mouseout on them

Steps to reproduce error:
 - Create a workflow
 - Add a random tool with multiple outputs (e.g. featureCounts
 - Click on one of the outputs to star it
 - Click on another of the outputs to star it
 - Click on one of these starred outputs to unstar it
 - Mouseover the other starred output
 - Move mouse away
 - Both outputs are now unstarred.

Not sure if this is also the case with usegalaxy.org

**Comment by erasche** [comment]
@mtekman for future reference galaxy issues you can file under the private usegalaxy-eu/issues project.

**Comment by erasche** [comment]
Can you re-test this for me @mtekman

**Comment by erasche** [comment]
Perfect. I'll file against galaxyproject/galaxy and close this then.
