### ISSUE TITLE
Need a post highlighting new features

### ISSUE THREAD

**Issue by erasche** [usegalaxy-eu/website#44]
- change tools in WF
- duplicate tool
- ... ?

users don't read release notes and release notes don't highlight the features with nice gifs like we will.

**Comment by bgruening** [comment]
is still relevant?

**Comment by erasche** [comment]
Yeah. Never wrote the user-facing release notes for 18.05.

**Comment by erasche** [comment]
Discussion in https://github.com/galaxyproject/galaxy/issues/7425
