### ISSUE TITLE
Calendar Events subscribable feed (iCal or other)

### ISSUE THREAD

**Issue by mtekman** [usegalaxy-eu/website#539]
I see the ability to add individual events to a calendar (ics)

![Screenshot_2020-11-02 Galaxy Community Conference (GCC) 2016](https://user-images.githubusercontent.com/20641402/97873453-eea24f80-1d17-11eb-9332-73b60e179981.png)

But is there a way to get a general iCal for all events?

**Comment by beatrizserrano** [comment]
Not sure if I understand well, but there is a Galaxy events calendar, is that what you meant @mtekman?

**Comment by bgruening** [comment]
And you have an RSS feed for events and posts ...

**Comment by beatrizserrano** [comment]
It's a public Google calendar, I've shared it with you

**Comment by beatrizserrano** [comment]
Maybe we can rephrase the issue: Is there a way to sync the events in the website and that Google calendar? (also discussed with @tnabtaf at some point)

**Comment by bgruening** [comment]
@mtekman https://galaxyproject.org/events/ the link in the second sentence.
