### ISSUE TITLE
make install missing jekyll-scholar and jekyll-twitter-plugin?

### ISSUE THREAD

**Issue by tnabtaf** [usegalaxy-eu/website#609]
Hi All,

I don't understand Jekyll, but it does offer helpful error messages.  After running `make install`, running `make run` tells me that these two gems are missing:

```
jekyll-scholar
jekyll-twitter-plugin
```

Running

`gem install --user-install *gem name*`

for each then allows the build to work.  Does `make install` need to be updated?  Or do I just need to be tougher?

Thanks, Dave C

**Comment by bgruening** [comment]
I hope my latest commit has fixed that and both deps are now installed with conda as well.
