### ISSUE TITLE
Adjust sort on events page

### ISSUE THREAD

**Issue by tnabtaf** [usegalaxy-eu/website#629]
Right now the events page on galaxyproject.eu sorts things in reverse chronological order, which means that events happening soon occur partway down the page, rather than at the top of the page.

I suggest breaking the events list into 2 parts.

* Top part, in chronological order, listing upcoming and current events
* Bottom part, in reverse chronological order, listing past events

This would put upcoming events at the top of the page,

Would this be a suitable issues for Papercuts?

**Comment by bgruening** [comment]
We can add a clear separation between the past-events and current-soon-to-happen events (`</hr>`?). Both lists can then be sorted in different ways.

The tricky part is to make sure that the table on the front page is still rendered in a meaningful way.

@OlegZharkov could you please look into this?

**Comment by OlegZharkov** [comment]
> Right now the events page on galaxyproject.eu 

just to clarify a bit, do you mean this one?
![image](https://user-images.githubusercontent.com/15801412/114012787-72d0a400-986f-11eb-8463-61841967a64a.png)

not the table on the front page?
![image](https://user-images.githubusercontent.com/15801412/114013156-e7a3de00-986f-11eb-8c53-f6cd2277d08f.png)

**Comment by tnabtaf** [comment]
@OlegZharkov Thanks for the question.  I meant the first one, European Galaxy Events, but I think the second one on the front page should also be reordered.

Also, if you think this is suitable as a paper-cut issue, we could label it as such, and then ask if @NickSto wants to take it on.  It might be good for Nick to mess with the EU site (or he may not be interested).
