### ISSUE TITLE
GTN update

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/website#651]
Highlight the new GTN feeds and recent enhancements: feeds, FAQs...

**Comment by OlegZharkov** [comment]
> Highlight the new GTN feeds and recent enhancements: feeds, FAQs...

hey, what kind of highlight do you have in mind?

**Comment by OlegZharkov** [comment]
> No, just writing a blog post telling a story :)

aaaah, you just wanted to create a post about it? Well, if there's nothing has to be implemented, I'm sorry for the noise ;)

**Comment by beatrizserrano** [comment]
@bebatut would you like to do this one?

**Comment by bebatut** [comment]
I could do that

**Comment by bgruening** [comment]
I think we should take the Atom/RSS feed and create a GH action that creates posts out of it. RSS should give us already the date/title and a small blurb that we need. Then we could link the post out to GTN.

**Comment by hexylena** [comment]
+1 to the atom/rss feed :)

```
$ curl --silent https://training.galaxyproject.org/training-material/feed.xml | xpath -q -e //entry/title
<title type="html">New Tutorial: Mutation calling, viral genome reconstruction and lineage/clade assignment from SARS-CoV-2 sequencing data</title>
<title type="html">New Tutorial: Visualization of RNA-Seq results with Volcano Plot in R</title>
<title type="html">New Tutorial: GitPod for contributing to the GTN</title>
<title type="html">New Tutorial: Genome Annotation with Apollo</title>
<title type="html">Oh no, it changed! Quick, to the archive menu.</title>
<title type="html">New Feature: Easy Abbreviation</title>
<title type="html">Contributing to BioBlend as a developer</title>
<title type="html">¿Hablas español?: The first curated tutorial in Spanish!</title>
<title type="html">New Tutorials: Whole transcriptome analysis of Arabidopsis thaliana</title>
<title type="html">New Feature: Video Player</title>
```

a script could definitely do this and create stub posts for each of these. (If you write that script, the GTN wants it!)

**Comment by bgruening** [comment]
proposal PR here: https://github.com/usegalaxy-eu/website/pull/748
