### ISSUE TITLE
Talk "Women in Science"

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/website#652]

**Comment by bebatut** [comment]
Do you mean adding an event for the website?

**Comment by beatrizserrano** [comment]
I was thinking more about a post afterwards describing the event, its purpose, how it went, your experience... but an event sounds good to me too :)

**Comment by bgruening** [comment]
Video here: https://www.youtube.com/watch?v=Il84WUPVaxc

**Comment by bebatut** [comment]
the video is for the BVCN conference. I need also to write a post about it....
