### ISSUE TITLE
Automatic image optimization

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/website#656]
Recently discussed with @tnabtaf: It would be nice to have image compression every time we upload images to this repo and the Hub. I don't know much about it but looks like that's possible using GitHub actions...

https://css-tricks.com/optimize-images-with-a-github-action/

Do you think that this can be a thing for our Code Day on Friday?

Thanks!

**Comment by bgruening** [comment]
Yes, please! I do it once in a while manually.

**Comment by davelopez** [comment]
I'll take a stab at it today :)
