### ISSUE TITLE
New paper "Robust and efficient single-cell Hi-C clustering with approximate k-nearest neighbor graphs"

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/website#687]
A post with a short intro and abstract, format similar to https://galaxyproject.eu/news?tag=paper

**Comment by bgruening** [comment]
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009014 and a new one from us.

**Comment by bgruening** [comment]
ping @joachimwolff
