### ISSUE TITLE
Need to fix the carrousel

### ISSUE THREAD

**Issue by bebatut** [usegalaxy-eu/website#81]
Many things are looking strange on the carrousel:

![screen shot 2018-06-27 at 19 01 31](https://user-images.githubusercontent.com/1842467/41988776-753a642c-7a3d-11e8-8ac8-e5cb395f2ca4.png)
![screen shot 2018-06-27 at 19 01 42](https://user-images.githubusercontent.com/1842467/41988777-755f6d12-7a3d-11e8-8691-c7acdafe77c0.png)
![screen shot 2018-06-27 at 19 01 48](https://user-images.githubusercontent.com/1842467/41988778-75759452-7a3d-11e8-819e-3cccfcfb9119.png)
![screen shot 2018-06-27 at 19 01 56](https://user-images.githubusercontent.com/1842467/41988780-758fdce0-7a3d-11e8-94d0-92ed68e22584.png)
![screen shot 2018-06-27 at 19 02 02](https://user-images.githubusercontent.com/1842467/41988781-75a972ae-7a3d-11e8-994a-95d7e5bcc294.png)

**Comment by erasche** [comment]
Oh, you're viewing it on a smaller than normal window. That's.. unfortunate. Ok, I'll do this tomorrow. 

But some are not easy to fix, data retention / acknowledgements, there are so many words. there is no hope to fix that issue I think.
