### ISSUE TITLE
Post about the COVID paper

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/website#837]
We didn't highlight [this paper](https://www.nature.com/articles/s41587-021-01069-1) and it was a big effort from our team, should we create a post?

**Comment by wm75** [comment]
:+1: Going to work on it later this week.

**Comment by bgruening** [comment]
and now there is already this one:

* https://www.biorxiv.org/content/10.1101/2022.01.14.476382v1.full.pdf
