### ISSUE TITLE
usegalaxy.eu reached 40,000 registered users

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/website#841]

**Comment by gallardoalba** [comment]
I'll write it tomorrow.

**Comment by gmauro** [comment]
Now, should be `exceeded` :)

**Comment by gallardoalba** [comment]
> Now, should be `exceeded` :)

Could you provide me some data about the number of users in the last 5 years in order to create a plot @gmauro?

**Comment by gmauro** [comment]
Sure!
