### ISSUE TITLE
blog post about the ML Videos

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#903]
https://gallantries.github.io/video-library/modules/machine-learning

@anuprulez is that a good idea? Do you wanna do that?

**Comment by anuprulez** [comment]
@bgruening honestly, I have no idea about it. Is it a permanent thing, setting up videos of various ML topics? or is it just for the Smörgåsbord training event? I am lacking some context here on what is expected to be done. thanks!

**Comment by bgruening** [comment]
its a permanent thing, a page with all ML video content ... people can bookmark that page etc ...

**Comment by anuprulez** [comment]
Thanks, just now had a chat with Helena. Would write a blog post and recognise Kaivan, Fotis, other people as well

**Comment by bgruening** [comment]
Cool, thanks!

**Comment by anuprulez** [comment]
https://github.com/usegalaxy-eu/website/pull/904

**Comment by bgruening** [comment]
Thanks Anup!
