### ISSUE TITLE
Post about the parper "Gut microbiota drives age-related oxidative stress and mitochondrial damage in microglia via the metabolite N6-carboxymethyllysine"

### ISSUE THREAD

**Issue by bebatut** [usegalaxy-eu/website#908]
Online on March, 3. 
DOI: 10.1038/s41593-022-01027-3. 
URL: https://www.nature.com/articles/s41593-022-01027-3

To do:
- [x] Add post
- [x] Add to bibtex

**Comment by anuprulez** [comment]
URL: https://www.nature.com/articles/s41593-022-01027-3 seems to be broken

**Comment by pavanvidem** [comment]
Maybe not yet online?

**Comment by anuprulez** [comment]
ah, could be, thanks :)

**Comment by bebatut** [comment]
Yes not online yet.
I will assign this issue to me as I participated in the paper
