### ISSUE TITLE
List of subdomains is too long :)

### ISSUE THREAD

**Issue by hexylena** [usegalaxy-eu/website#987]
![image](https://user-images.githubusercontent.com/458683/173086214-ba868b1a-96d2-4504-8499-0b6deb8e5817.png)

it's a great success! but now some are cut off.

**Comment by beatrizserrano** [comment]
this will hopefully disappear soon, I am working on the migration to the Hub :)

**Comment by hexylena** [comment]
Nice!

**Comment by beatrizserrano** [comment]
I'll close this, since the full list is here: https://galaxyproject.org/eu/subdomains/
Thank you @hexylena :)
