### ISSUE TITLE
ELIXIR AHM summary 

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/website#988]
It would be nice if we can add a blog post with all the things that we have done and link the content to our slides, posters etc ...

@beatrizserrano @anuprulez @EngyNasr @bebatut 

@EngyNasr maybe you can make a start?

**Comment by anuprulez** [comment]
Can we use this doc to collect everyone's contribution: https://docs.google.com/document/d/1Q2EcfWF-pOhJwktCuleoIgY65kJamJktLZ-XOxbBQnk/edit?usp=sharing?

**Comment by EngyNasr** [comment]
https://github.com/usegalaxy-eu/website/pull/993

**Comment by bgruening** [comment]
Can we close this one?
